### ISSUE TITLE
Envoy Load Balancer: Connection reset by peer

### ISSUE THREAD

**Issue by activeshadow** [thoughtworks/maeve-csms#35]
Is anyone else having issues with the Envoy load balancer present in the Docker Compose deployment? I am not able to talk to the manager service's API on port 9410 (or any of the other services the load balancer is acting as a reverse proxy for) through the load balancer. The manager's API is not the problem since I can curl the API from the host if I map the manager's API port to a local port, and I can curl the API port from within the load balancer container.

I've tried debugging Envoy to see what the issue is but even with it's log level set to `debug` I'm not seeing anything obvious. Is there a reason why such a complex reverse proxy solution, or even a reverse proxy at all, is being used as part of the default Docker Compose config? I see the need for something like Envoy in a large-scale production deployment of MaEVe in Kubernetes for example, but not in a Docker Compose style deployment.

**Comment by subnova** [comment]
If you see that Envoy isn't responding, you may find that the restarting that specific docker container resolves your problems (`docker compose down lb && docker compose up lb -d`). The use of Envoy in the provided docker compose file makes it possible to test the independent scaling of the gateway and manager components, but it isn't required.

**Comment by subnova** [comment]
I've pushed a change to the docker-compose.yaml file that delays Envoy startup until after the gateway & manager components are running which I hope addresses the issue.

**Comment by activeshadow** [comment]
@subnova I just tested your updates to docker-compose.yml and unfortunately I'm still getting errors when using curl to hit the API endpoints.
